server:
  port: 10025


dataMaker.jdbc:
  type: mysql
  driverClassName: com.mysql.jdbc.Driver
  jdbcUrl:
  username:
  password:
  maximumPoolSize: 10 #连接池中允许的最大连接数。
  minimumIdle: 1 #连接池中允许的最小连接数。
  maxLifetime: 2000000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
  connectionTimeout: 30000 #等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
  idleTimeout: 30000 #一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
  autoCommit: true